### ISSUE TITLE
Cannot complete install due to abandoned package

### ISSUE THREAD

**Issue by kaylak4520** [seatplus/seatplus#2]
While following the exact install instructions listed on https://seatplus.net/docs/installation , the following output is displayed: 
  - Installing seatplus/auth (2.0.1): Extracting archive
  - Installing inertiajs/inertia-laravel (v0.5.4): Extracting archive
  - Installing conedevelopment/i18n (v1.3.0): Extracting archive
  - Installing seatplus/web (2.2.0): Extracting archive
59 package suggestions were added by new dependencies, use `composer suggest` to see details.
Package fruitcake/laravel-cors is abandoned, you should avoid using it. No replacement was suggested.
Package spatie/data-transfer-object is abandoned, you should avoid using it. Use spatie/laravel-data instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In CheckJobsCommand.php line 67:

                                   
  Class "Faker\Factory" not found  
                                   

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
[13-Mar-2023 17:58:50] NOTICE: Terminating ...
[13-Mar-2023 17:58:50] NOTICE: exiting, bye-bye!
ERROR: 1

Follow the steps at https://seatplus.net/docs/installation under the section "Prepare your app"

**Expected behavior**
The software should install by following the listed installation instructions

**Server Info:)
 - OS: Ubuntu 22.04 Server

Installation does not finish.

**Comment by herpaderpaldent** [comment]
😳 oh ... thank you for reporting i`ll have a look asap

**Comment by herpaderpaldent** [comment]
Thanks for reporting. I haven't had the chance yet to test it out but this should have fixed the issue. I'll test it out tonight but if you are able to do it earlier, please let me know.
